version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_password: root
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - mongodb-data:/data/db  # <-- REFERENCING THE VOLUME
# --- New Top-Level Section ---
volumes:
  mongodb-data:


