version: '4'
services:
  inventory-mysql:
    image: mysql:8.3.0
    container_name: inventory-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/inventory_data:/var/lib/mysql